# Run r cmd check
name: call-r-cmd-check
# on specifies the build triggers. See more info at https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  # The default build trigger is to run the action on every push and pull request, for any branch
  push:

jobs:
  call-workflow:
    uses: nmfs-ost/ghactions4r/.github/workflows/r-cmd-check.yml@main
